// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['main']['Calculator']['Add'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['main']['Calculator']['Startup'](arg1);
}

export function Subtract(arg1, arg2) {
  return window['go']['main']['Calculator']['Subtract'](arg1, arg2);
}
